version: '3'
services:
  api:
    build: ./api
    container_name: openworld-api-service
    volumes:
      - ./api/api:/code/api
    env_file:
      - ./api/.${RUN_ENV}.env
    ports:
      - "5000:5000"
    tty: true
  db:
    build: ./db
    container_name: openworld-db-service
    env_file:
      - ./db/.${RUN_ENV}.env
    tty: true
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/db:/db



